### ISSUE TITLE
How can use this?

### ISSUE THREAD

**Issue by zSteley** [Coderx-Gamer/lectern-crash#1]
I want to use this. I Installed fabric loader and then drop the mod to mods folder, but In-game don't appear nothing!

**Comment by TaxEvasiqn** [comment]
Don't use double negatives

**Comment by zSteley** [comment]
What means double negatives?

**Comment by Cladthe2nd** [comment]
grammar lol

**Comment by OctonalXX** [comment]
Do you install **both** Fabric **API** and Fabric **Loader**?

**Comment by Coderx-Gamer** [comment]
could be incompatible mods causing the button to render in second priority, or a button is overlaid over the crash server button making it not really visible.

**Comment by FrostX-Official** [comment]
can it happen if i use wurst-1.18.2?
