### ISSUE TITLE
i downloaded it what next idk how to do it

### ISSUE THREAD

**Issue by Cladthe2nd** [Coderx-Gamer/lectern-crash#2]

**Comment by erxson** [comment]
just open lectern gui and press "crash server" button

**Comment by Cladthe2nd** [comment]
i put the file in mods folder and nothing is happening

**Comment by OctonalXX** [comment]
This mod needs Fabric **API** and it's **loader** so check for any errors and start the game, next get a lectern and


> just open lectern gui and press "crash server" button

[Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Fabric Loader](https://fabricmc.net/use/installer/)
